/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 scene.gltf 
Author: jgrounds (https://sketchfab.com/jgrounds)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/web-programming-vr-f1027f15996446b1a242cd34b8007d17
Title: Web Programming VR
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.007}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[-15, 106.554, -87.048]}>
            <group position={[15, -1.355, 87.048]}>
              <mesh geometry={nodes.keyboardcord_mousepad_0.geometry} material={materials.mousepad} />
              <mesh geometry={nodes.Cap_1_mousepad_0.geometry} material={materials.mousepad} position={[-30.029, 2.488, -184.723]} rotation={[0.04, -0.304, 2.692]} />
              <mesh geometry={nodes.Cap_2_mousepad_0.geometry} material={materials.mousepad} position={[111.867, -56.295, -198.13]} rotation={[-3.077, -0.771, 0.339]} />
            </group>
            <group position={[-15, 1.355, -87.048]}>
              <mesh geometry={nodes.Keyboard_3_keyboard_0.geometry} material={materials.keyboard} />
              <mesh geometry={nodes.Keyboard_3_keyboardKeys_0.geometry} material={materials.keyboardKeys} />
            </group>
          </group>
          <group position={[142.911, 232.743, -858.902]}>
            <mesh geometry={nodes.Mountain_mountain_0.geometry} material={materials.mountain} position={[-142.911, -35.032, 423.713]} rotation={[0.276, 0, 0]} />
            <mesh geometry={nodes.sky_sky_0.geometry} material={materials.material} position={[-142.911, -18.235, 558.389]} rotation={[-Math.PI / 2, 0, 0]} />
          </group>
          <group position={[0, 339.486, 0]}>
            <mesh geometry={nodes.LightFixture_1_keyboard_0.geometry} material={materials.keyboard_0} />
            <mesh geometry={nodes.LightFixture_1_diffuseglass_0.geometry} material={materials.diffuseglass} />
          </group>
          <group position={[0, 210, -289.821]}>
            <mesh geometry={nodes.window_1_frame_0.geometry} material={materials.frame} />
            <mesh geometry={nodes.window_1_glass_0.geometry} material={materials.glass} />
          </group>
          <group position={[0, 180.467, -0.063]}>
            <mesh geometry={nodes.front_1_front_0.geometry} material={materials.front} position={[0, -0.467, -296.333]} />
            <mesh geometry={nodes.back_back_0.geometry} material={materials.back} position={[0, -0.467, 296.082]} rotation={[Math.PI / 2, 0, 0]} />
            <mesh geometry={nodes.left_left_0.geometry} material={materials.left} position={[-296, 0.933, 0.063]} rotation={[0, 0, -Math.PI / 2]} />
            <mesh geometry={nodes.right_right_0.geometry} material={materials.right} position={[296, 0.933, 0.063]} rotation={[0, 0, -Math.PI / 2]} />
            <mesh geometry={nodes.top_top_0.geometry} material={materials.material_22} position={[0, 179.533, 0.063]} />
            <mesh geometry={nodes.bottom_bottom_0.geometry} material={materials.bottom} position={[0, -180.467, 0.063]} />
          </group>
          <mesh geometry={nodes.logo_logo_0.geometry} material={materials.logo} position={[0, 210.488, -226.148]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.addMonitor_1_addmonitor_0.geometry} material={materials.addmonitor} position={[-124.291, 158.55, -206.381]} rotation={[Math.PI / 2, 0, -0.175]} />
          <mesh geometry={nodes.addMonitor_addmonitor_0.geometry} material={materials.addmonitor} position={[117.092, 158.55, -201.336]} rotation={[Math.PI / 2, 0, Math.PI / 9]} />
          <mesh geometry={nodes.backTrim_1_frame_0.geometry} material={materials.frame} position={[6.689, 11.645, 290.216]} />
          <mesh geometry={nodes.Chair_1_Chair_0.geometry} material={materials.Chair} position={[-11.789, 99.154, -94.249]} />
          <mesh geometry={nodes.frontTrim_1_frontTrim_0.geometry} material={materials.frontTrim} position={[4.162, 11.645, -291.574]} />
          <mesh geometry={nodes.rightTrim_1_frame_0.geometry} material={materials.frame} position={[290.841, 11.927, 2.184]} />
          <mesh geometry={nodes.leftTrim_1_frame_0.geometry} material={materials.frame} position={[-290.458, 11.645, 1.424]} />
          <mesh geometry={nodes.Mouse_1_Mouse_0.geometry} material={materials.Mouse} position={[62.601, 82.603, -228.087]} />
          <mesh geometry={nodes.desktop_desktop1_0.geometry} material={materials['desktop.1']} position={[110, 43.429, -169.579]} />
          <mesh geometry={nodes.Monitor2_1_Monitor2_0.geometry} material={materials.Monitor2} position={[44.892, 149.161, -215.828]} />
          <mesh geometry={nodes.Monitor1_1_Monitor1_0.geometry} material={materials.Monitor1} position={[-50.892, 149.161, -215.828]} />
          <mesh geometry={nodes.desk_1_desk1_0.geometry} material={materials['desk.1']} position={[0, 55.626, -216.785]} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
